# Generated by Django 5.2.11 on 2026-02-19 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_reactions_and_replies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "-created_at"], name="idx_message_room_created"
            ),
        ),
    ]
